### ISSUE TITLE
Cannot build under MacOS - error in PortBlock.cpp

### ISSUE THREAD

**Issue by dangom** [TimVanMourik/Porcupine#12]
Hi Tim,

I wanted to use nipype to code up an ICC calculator and I figured that'd be a nice opportunity to try Porcupine again. Unfortunately, I cannot get it to compile:

Here's the error I get:
``
src/NodeTreeEditor/PortBlock.cpp:152:15: error: no member named 'removeRow' in 'QFormLayout'
    m_layout->removeRow(_row);
``
``
Makefile:1419: recipe for target 'obj/PortBlock.o' failed
make: *** [obj/PortBlock.o] Error 1
    ~~~~~~~~  ^
1 error generated.
``

Any suggestions?

Thx
``
qt@5.7: stable 5.7.1
``

**Comment by TimVanMourik** [comment]
Yes, the reason is simply that the program is written in a newer version of Qt. Specifically the 'removeRow' is new. Simply update your Qt version and all problems are solved!

**Comment by dangom** [comment]
In which case I'd recommend updating the README, as it makes reference to 5.7.0.

**Comment by TimVanMourik** [comment]
Good point! I changed it recently on the Getting Started page, but forgot to do so in the README
