### ISSUE TITLE
[Question] How do I install it on Linux?

### ISSUE THREAD

**Issue by tashrifbillah** [TimVanMourik/Porcupine#35]
May be I am missing something, but your release page has source code beside MAC and Windows installers only.

**Comment by tashrifbillah** [comment]
@TimVanMourik

**Comment by PeerHerholz** [comment]
Ahoi hoi @tashrifbillah,

you're right in that there are installers only for macOS and Windows. On linux, porcupine needs to compiled and run through [Qt Creator](https://www.qt.io/developers) after downloading the source code. Please also note that porcupine was superceded by [Giraffe Tools](https://github.com/TimVanMourik/GiraffeTools). @TimVanMourik please correct my pointers, if I'm wrong.

HTH, cheers, Peer

**Comment by tashrifbillah** [comment]
Hi Peer,

The README mentions:

> Soon, Porcupine will move to the clouds! As a web application, it will be a Graphical Interface for Reproducible Analysis oF workFlow Experiments, giraffe. Watch the progress in the repository (https://github.com/TimVanMourik/GiraffeTools) or the output on www.giraffe.tools.

Assuming it to be in-progress, I didn't bother checking out. I am going to need something local anyway so `Porcupine` would be my choice over some web-interface based tool.

> On linux, porcupine needs to compiled and run through Qt Creator after downloading the source code.

Is there a building instruction somewhere?

**Comment by tashrifbillah** [comment]
I think I found something. 

https://github.com/TimVanMourik/Porcupine/blob/master/Dockerfile

I am going to try the steps locally.

**Comment by tashrifbillah** [comment]
Built gracefully on my CentOS 7 machine:

# Qt

> ~/Qt/5.12.3/gcc_64/bin/qmake --version
```
QMake version 3.1
Using Qt version 5.12.3 in /home/tb571/Qt/5.12.3/gcc_64/lib
```

# Build instruction

```
git clone https://github.com/TimVanMourik/Porcupine.git
cd Porcupine
export LD_LIBRARY_PATH=/home/tb571/Qt/5.12.3/gcc_64/lib:$LD_LIBRARY_PATH
qmake
make
```

After successful building, launch `Porcupine/bin/Porcupine`.

May be we can enhance the documentation with the above?

**Comment by TimVanMourik** [comment]
Hi @tashrifbillah, thanks for reaching out! And thanks @PeerHerholz for answering :) 

So the web application can do all and more that this stand-alone app can do, so I'm not developing this version any longer. Check out the introduction post about GiraffeTools here: https://medium.com/@TimVanMourik/giraffetools-a-generic-online-workflow-editor-8e48e288a6c7. Thanks for mentioning that point in the README, I'll update it right away. 

With regard to your original question, I'm glad you managed to build it! Indeed, it's just a `qmake && make` that should do the trick. If you'd like to add this to the README, I'll happily merge it in a PR!

**Comment by tashrifbillah** [comment]
Yeah, I can do that.

Label: Doc-Enhancement
Assign: @tashrifbillah

I'll checkout your other tool.
