### ISSUE TITLE
Porcupine.app hanging on MacOS Sierra

### ISSUE THREAD

**Issue by dangom** [TimVanMourik/Porcupine#4]
Hi Tim,

App seems to hang and behave really slow under MacOS 10.12.4.

Qt specs:
```
$ brew info qt@5.7
qt@5.7: stable 5.7.1 (bottled), HEAD [keg-only]
Cross-platform application and UI framework

$ qmake --version
QMake version 3.0
Using Qt version 5.7.1 in /usr/local/Cellar/qt@5.7/5.7.1/lib
```

App built with `qmake Porcupine.pro && make` on master branch.

Any ideas where the issue may be coming from?

**Comment by TimVanMourik** [comment]
Hi Daniel!
Yes I do! In fact I fixed it today, but that's not in the release yet. The reason is that a QGraphicsView within a QLayout within a QSlicer seems to cause circular updatings, but I'll spare you the details. I'll put up a new release this week!

**Comment by dangom** [comment]
Hi Tim!
Thanks for the fast answer.
I just cloned the repo and built from src on the latest commit some minutes ago, so if you refer to code changes that are not on Github yet, then I'll just wait.

I didn't try the .dmg release from 29 days ago.

**Comment by TimVanMourik** [comment]
That's right, it wasn't fully fit for a push yet, but should be done by
tomorrow.

**Comment by TimVanMourik** [comment]
Done. At least on Windows the problem's been resolved. Haven't tried Mac yet.

**Comment by dangom** [comment]
Issue solved.
